CREATE OR REPLACE TABLE ex.competition_person_statistics_basketball (
  competitionId int NOT NULL,
  personId int NOT NULL,
  leagueId int NOT NULL,
  teamId int NOT NULL,
  periodNumber int NOT NULL,
  periodType varchar(10) NOT NULL DEFAULT 'REGULAR',
  homeAway varchar(255) NOT NULL DEFAULT 'ALL',
  winLoss varchar(4) NOT NULL DEFAULT 'ALL',
  inConference varchar(4) NOT NULL DEFAULT 'ALL',
  matchType varchar(9) NOT NULL DEFAULT 'ALL',
  player int,
  coach int,
  starter int,
  sAssists int,
  sAssistsDefensive int,
  sAssistsTurnoverRatio decimal(6,2),
  sAssistsPercentage decimal(6,2),
  sBlocks int,
  sBlocksPercentage decimal(6,2),
  sBlocksReceived int,
  sDefensiveRating decimal(6,2),
  sDraws int,
  sEfficiency decimal(6,2),
  sEfficiencyCustom decimal(6,2),
  sEfficiencyGameScore decimal(6,2),
  sFieldGoalsAttempted int,
  sFieldGoalsEffectivePercentage decimal(6,2),
  sFieldGoalsMade int,
  sFieldGoalsPercentage decimal(6,2),
  sForfeitsAgainst int,
  sForfeitsFor int,
  sFoulsCoachDisqualifying int,
  sFoulsCoachTechnical int,
  sFoulsDisqualifying int,
  sFoulsOn int,
  sFoulsOffensive int,
  sFoulsPersonal int,
  sFoulsTechnical int,
  sFoulsTotal int,
  sFoulsUnsportsmanlike int,
  sFreeThrowsAttempted int,
  sFreeThrowsMade int,
  sFreeThrowsPercentage decimal(6,2),
  sGames int,
  sGamesStarted int,
  sLosses int,
  sMinus int,
  sMinutes decimal(10,6) NOT NULL,
  sMVPVotes int,
  sOffensivePointsPerPossession decimal(6,2),
  sOffensiveRating decimal(6,2),
  sPER decimal(6,2),
  sPlus decimal(6,2),
  sPlusMinusPoints decimal(6,2),
  sPlusMinusPointsAdjusted decimal(6,2),
  sPoints int,
  sPointsAgainst int,
  sPointsSecondChance int,
  sPossessions decimal(6,2),
  sReboundsDefensive int,
  sReboundsDefensivePercentage decimal(6,2),
  sReboundsOffensive int,
  sReboundsOffensivePercentage decimal(6,2),
  sReboundsPercentage decimal(6,2),
  sReboundsTotal int,
  sResults varchar(60) DEFAULT '',
  sSteals int,
  sStealsPercentage decimal(6,2),
  sThreePointersAttempted int,
  sThreePointersMade int,
  sThreePointersPercentage decimal(6,2),
  sTrueShootingAttempts int,
  sTrueShootingPercentage decimal(6,2),
  sTurnovers int,
  sTurnoversPercentage decimal(6,2),
  sTwoPointersAttempted int,
  sTwoPointersMade int,
  sTwoPointersPercentage decimal(6,2),
  sWins int,
  updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sGamesTeam int,
  sGamesTeamPercentage decimal(6,2),
  sSecondChancePointsAttempted int,
  sSecondChancePointsMade int,
  sSecondChancePointsPercentage decimal(6,2),
  sPointsInThePaint int,
  sPointsInThePaintMade int,
  sPointsInThePaintAttempted int,
  sPointsInThePaintPercentage decimal(6,2),
  sPointsFastBreak int,
  sFastBreakPointsMade int,
  sFastBreakPointsAttempted int,
  sFastBreakPointsPercentage decimal(6,2),
  sFouledOut int DEFAULT NULL,
  sUsagePercentage decimal(6,2),
  PRIMARY KEY (competitionId,personId,teamId,periodNumber,periodType,homeAway,winLoss,inConference,matchType),
  CONSTRAINT competition_person_statistics_basketball_ibfk_1 FOREIGN KEY (leagueId) REFERENCES ex.league (leagueId),
  CONSTRAINT competition_person_statistics_basketball_ibfk_2 FOREIGN KEY (competitionId) REFERENCES ex.competition (competitionId),
  CONSTRAINT competition_person_statistics_basketball_ibfk_3 FOREIGN KEY (personId) REFERENCES ex.person (personId)
);    
