CREATE OR REPLACE TABLE ex.competition (
  competitionId int NOT NULL,
  leagueId int NOT NULL,
  competitionName varchar(100) DEFAULT '',
  competitionAbbrev varchar(50) DEFAULT '',
  startDate date DEFAULT NULL,
  endDate date DEFAULT NULL,
  year int,
  season varchar(50) DEFAULT '',
  numberCompetitors int,
  current_ int,
  gender varchar(10) DEFAULT '',
  ageGroup varchar(30) DEFAULT '',
  representation varchar(30) DEFAULT '',
  standard varchar(30) DEFAULT '',
  competitionOrder int,
  groupingOrder int,
  groupingKey varchar(50) DEFAULT '',
  grade varchar(50) DEFAULT '',
  competitorType varchar(10) DEFAULT '',
  includeInCareerStatistics int,
  numberOfPeriods int,
  periodLength int,
  extraTime int,
  extraTimeLength int,
  finalsPositions int,
  facebook varchar(150) DEFAULT '',
  website varchar(150) DEFAULT '',
  twitter varchar(20) DEFAULT '',
  keywords varchar(255) DEFAULT '',
  externalId varchar(50) DEFAULT '',
  updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ticketURL varchar(100) DEFAULT '',
  competitionNameInternational varchar(100) DEFAULT '',
  competitionAbbrevInternational varchar(50) DEFAULT '',
  standingConfigurationId int,
  PRIMARY KEY (competitionId),
  CONSTRAINT competition_ibfk_1 FOREIGN KEY (leagueId) REFERENCES ex.league (leagueId)
);    
