CREATE OR REPLACE TABLE ex.fixtured_match (
  matchId int NOT NULL,
  competitionId int,
  venueId int,
  leagueId int,
  poolNumber int,
  phaseName varchar(100) DEFAULT '',
  matchName varchar(100) DEFAULT '',
  roundNumber varchar(30) DEFAULT '',
  roundDescription varchar(30) DEFAULT '',
  matchNumber int,
  matchStatus varchar(20) DEFAULT '',
  extraPeriodsUsed int,
  matchTime datetime DEFAULT NULL,
  enddate date DEFAULT NULL,
  timeActual datetime DEFAULT NULL,
  timeEndActual datetime DEFAULT NULL,
  durationActual decimal(8,2),
  temperature decimal(8,2),
  attendance int,
  duration decimal(8,2),
  weather varchar(50) DEFAULT '',
  twitterHashtag varchar(50) DEFAULT '',
  liveStream int,
  matchType varchar(20) DEFAULT '',
  keywords varchar(255) DEFAULT '',
  resultTags varchar(255) DEFAULT '',
  nextMatchId int NOT NULL,
  placeIfWon int NOT NULL,
  placeIfLost int NOT NULL,
  externalId varchar(50) DEFAULT '',
  updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ticketURL varchar(100) DEFAULT '',
  matchTimeUTC datetime DEFAULT NULL,
  atNeutralVenue int,
  inConference int,
  timezone varchar(50) DEFAULT '',
  statsSource varchar(64) DEFAULT NULL,
  matchDataUpdated timestamp NULL DEFAULT NULL,
  tournamentId int DEFAULT NULL,
  PRIMARY KEY (matchId),
  CONSTRAINT fixtured_match_ibfk_1 FOREIGN KEY (leagueId) REFERENCES ex.league (leagueId),
  CONSTRAINT fixtured_match_ibfk_2 FOREIGN KEY (competitionId) REFERENCES ex.competition (competitionId)
);      