CREATE OR REPLACE TABLE ex.match_person_statistics_basketball (
  matchId int NOT NULL,
  competitionId int,
  teamId int NOT NULL,
  personId int NOT NULL,
  leagueId int NOT NULL,
  shirtNumber varchar(30) DEFAULT '',
  playingPosition varchar(30) DEFAULT '',
  periodNumber int NOT NULL,
  periodType varchar(10) NOT NULL DEFAULT 'REGULAR',
  participated int,
  DNPReason varchar(250) DEFAULT '',
  isPlayer int,
  isTeamOfficial int,
  isStarter int,
  sAssists int,
  sAssistsDefensive int,
  sAssistsTurnoverRatio decimal(6,2),
  sBlocks int,
  sBlocksReceived int,
  sDefensiveRating decimal(6,2),
  sEfficiency decimal(6,2),
  sEfficiencyCustom decimal(6,2),
  sEfficiencyGameScore decimal(6,2),
  sFieldGoalsAttempted int,
  sFieldGoalsEffectivePercentage decimal(6,2),
  sFieldGoalsMade int,
  sFieldGoalsPercentage decimal(6,2),
  sFoulsCoachDisqualifying int,
  sFoulsCoachTechnical int,
  sFoulsDisqualifying int,
  sFoulsOffensive int,
  sFoulsOn int,
  sFoulsPersonal int,
  sFoulsTechnical int,
  sFoulsUnsportsmanlike int,
  sFreeThrowsAttempted int,
  sFreeThrowsMade int,
  sFreeThrowsPercentage decimal(6,2),
  sMinus decimal(6,2),
  sMinutes decimal(10,6) NOT NULL,
  sMVPVotes int,
  sOffensiveRating decimal(6,2),
  sPER decimal(6,2),
  sPlus decimal(6,2),
  sPlusMinusPoints int,
  sPoints int,
  sPointsSecondChance int,
  sReboundsDefensive int,
  sReboundsDefensivePercentage decimal(6,2),
  sReboundsOffensive int,
  sReboundsOffensivePercentage decimal(6,2),
  sReboundsPercentage decimal(6,2),
  sReboundsTotal int,
  sSteals int,
  sStealsPercentage decimal(6,2),
  sThreePointersAttempted int,
  sThreePointersMade int,
  sThreePointersPercentage decimal(6,2),
  sTrueShootingAttempts decimal(6,2),
  sTrueShootingPercentage decimal(6,2),
  sTurnovers int,
  sTurnoversPercentage decimal(6,2),
  sTwoPointersMade int,
  sTwoPointersAttempted int,
  sTwoPointersPercentage decimal(6,2),
  externalId varchar(50) DEFAULT '',
  updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sSecondChancePointsAttempted int,
  sSecondChancePointsMade int,
  sSecondChancePointsPercentage decimal(6,2),
  sPointsInThePaint int,
  sPointsInThePaintMade int,
  sPointsInThePaintAttempted int,
  sPointsInThePaintPercentage decimal(6,2),
  sPointsFastBreak int,
  sFastBreakPointsMade int,
  sFastBreakPointsAttempted int,
  sFastBreakPointsPercentage decimal(6,2),
  sFouledOut int DEFAULT NULL,
  sUsagePercentage decimal(6,2),
  PRIMARY KEY (matchId,teamId,personId,periodNumber,periodType),
  CONSTRAINT match_person_statistics_basketball_ibfk_1 FOREIGN KEY (leagueId) REFERENCES ex.league (leagueId),
  CONSTRAINT match_person_statistics_basketball_ibfk_2 FOREIGN KEY (competitionId) REFERENCES ex.competition (competitionId),
  CONSTRAINT match_person_statistics_basketball_ibfk_3 FOREIGN KEY (matchId) REFERENCES ex.fixtured_match (matchId),
  CONSTRAINT match_person_statistics_basketball_ibfk_4 FOREIGN KEY (teamId) REFERENCES ex.team (teamId)
) ;