CREATE OR REPLACE TABLE ex.person (
  personId int NOT NULL,
  leagueId int NOT NULL,
  firstName varchar(50) DEFAULT '',
  familyName varchar(50) DEFAULT '',
  TVName varchar(50) DEFAULT '',
  scoreboardName varchar(50) DEFAULT '',
  dob date DEFAULT NULL,
  gender varchar(10) DEFAULT '',
  nickName varchar(50) DEFAULT '',
  height decimal(8,2),
  weight decimal(8,2),
  dominantHand varchar(10) DEFAULT '',
  dominantFoot varchar(10) DEFAULT '',
  internationalReference varchar(30) DEFAULT '',
  nationality varchar(100) DEFAULT '',
  nationalityCode varchar(100) DEFAULT '',
  nationalityCodeIOC varchar(100) DEFAULT '',
  sportCountryCode varchar(20) DEFAULT '',
  sportCountry varchar(100) DEFAULT '',
  facebook varchar(150) DEFAULT '',
  website varchar(150) DEFAULT '',
  twitter varchar(20) DEFAULT '',
  defaultShirtNumber varchar(10) DEFAULT '',
  defaultPlayingPosition varchar(30) DEFAULT '',
  primaryClubId int,
  primaryTeamId int,
  keywords varchar(255) DEFAULT '',
  externalId varchar(50) DEFAULT '',
  updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  internationalFirstName varchar(50) DEFAULT '',
  internationalFamilyName varchar(50) DEFAULT '',
  namePronunciation varchar(50) DEFAULT '',
  PRIMARY KEY (personId),
  CONSTRAINT person_ibfk_1 FOREIGN KEY (leagueId) REFERENCES ex.league (leagueId)
) ;        
