CREATE OR REPLACE TABLE ex.team (
  teamId int NOT NULL,
  leagueId int NOT NULL,
  clubId int NOT NULL,
  teamName varchar(100) DEFAULT '',
  teamNickname varchar(50) DEFAULT '',
  teamCode varchar(3) DEFAULT '',
  status varchar(20) DEFAULT '',
  address1 varchar(200) DEFAULT '',
  address2 varchar(200) DEFAULT '',
  address3 varchar(200) DEFAULT '',
  suburb varchar(100) DEFAULT '',
  state varchar(50) DEFAULT '',
  postalCode varchar(15) DEFAULT '',
  country varchar(100) DEFAULT '',
  countryCode varchar(2) DEFAULT '',
  countryCodeIOC varchar(3) DEFAULT '',
  phone varchar(20) DEFAULT '',
  fax varchar(20) DEFAULT '',
  email varchar(150) DEFAULT '',
  facebook varchar(150) DEFAULT '',
  website varchar(150) DEFAULT '',
  twitter varchar(20) DEFAULT '',
  internationalReference varchar(100) DEFAULT '',
  keywords varchar(250) DEFAULT '',
  externalId varchar(50) DEFAULT '',
  updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ticketURL varchar(100) DEFAULT '',
  teamNameInternational varchar(100) DEFAULT '',
  teamNicknameInternational varchar(50) DEFAULT '',
  teamCodeInternational varchar(3) DEFAULT '',
  colourPrimary varchar(6) DEFAULT '',
  colourSecondary varchar(6) DEFAULT '',
  divisionId int NOT NULL,
  conferenceId int NOT NULL,
  rankingIndex decimal(10,5) NOT NULL,
  PRIMARY KEY (teamId),
  CONSTRAINT team_ibfk_1 FOREIGN KEY (leagueId) REFERENCES ex.league (leagueId)
) ;    