CREATE OR REPLACE TABLE ex.venue (
  venueId int NOT NULL,
  leagueId int NOT NULL,
  locationId int,
  status varchar(20) DEFAULT '',
  venueName varchar(100) DEFAULT '',
  surfaceName varchar(100) DEFAULT '',
  venueNickname varchar(50) DEFAULT '',
  venueCode varchar(50) DEFAULT '',
  address1 varchar(200) DEFAULT '',
  address2 varchar(200) DEFAULT '',
  address3 varchar(200) DEFAULT '',
  suburb varchar(100) DEFAULT '',
  state varchar(50) DEFAULT '',
  postalCode varchar(15) DEFAULT '',
  country varchar(100) DEFAULT '',
  countryCode varchar(2) DEFAULT '',
  countryCodeIOC varchar(3) DEFAULT '',
  phone varchar(20) DEFAULT '',
  fax varchar(20) DEFAULT '',
  email varchar(150) DEFAULT '',
  facebook varchar(150) DEFAULT '',
  website varchar(150) DEFAULT '',
  twitter varchar(20) DEFAULT '',
  timezone varchar(30) DEFAULT '',
  latitude decimal(12,6),
  longitude decimal(12,6),
  seatingCapacity int,
  keywords varchar(250) DEFAULT '',
  externalId varchar(50) DEFAULT '',
  updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ticketURL varchar(100) DEFAULT '',
  yearBuilt int,
  rating int,
  venueNameInternational varchar(100) DEFAULT '',
  venueNicknameInternational varchar(50) DEFAULT '',
  venueCodeInternational varchar(50) DEFAULT '',
  PRIMARY KEY (venueId),
  CONSTRAINT venue_ibfk_1 FOREIGN KEY (leagueId) REFERENCES ex.league (leagueId)
) ;        
