CREATE OR REPLACE TABLE LD_26_PLC_CANDIDATES
(	"ID" NUMBER, 
    "SDT_ID" NUMBER,
     "ZPT_ID" NUMBER,
	"STEVILKA_DOKUMENTA" VARCHAR2(50),
	"ISK_ID" NUMBER,
    "SDT_DATVNO" DATE,	
    "DATVNO" DATE, 
    "DATUM_DO_OO" DATE,
    "VELJAVNOST_SPR_OD" DATE, 
    "VELJAVNOST_ZAC_DOK" DATE, 
    "VELJAVNOST_POT_DOK" DATE,
    "DATUM_STATUSA_ORG" DATE,
	"ST_PLC" NUMBER,	
	"ST_PLC_DTL" NUMBER,
    "SSK_ID" NUMBER, 
    "SIFRA" VARCHAR2(5),
	"TP_PLC" NUMBER,
    "SYS_DT" TIMESTAMP,
    "RANK" NUMBER 	    
);

CREATE OR REPLACE TABLE LD_26_PLC_CMP_42_DVOJCKI
(   "SDT_ID" NUMBER,  
    "ZPT_ID" NUMBER,
	"EXT_REF" VARCHAR2(50),
	"ISK_ID" NUMBER,
	"ZVE_ID" NUMBER,
    "PSD_ID" NUMBER,
	"PRD_EXT_REF" VARCHAR2(50),	
    "SDT_DATVNO" DATE,	
    "DT_VLD_BSN_BEG" DATE, 
    "DT_VLD_SRC_BEG" DATE, 
    "DT_VLD_SRC_BEG_INCR" TIMESTAMP, 
    "VELJAVNOST_ZAC_KRIT" DATE,
    "VELJAVNOST_POT_KRIT" DATE, 
	"ST_PLC_CMP" NUMBER,	
	"ST_PLC_CMP_DTL" NUMBER,
    "SSK_ID" NUMBER, 
    "TP_PLC" NUMBER, 
    "RN" NUMBER
);

CREATE OR REPLACE TABLE GEN_PLC 
   (	"ID_SLOT" NUMBER, 
	"AGM_EXT_REF" VARCHAR2(50 ), 
	"AGM_ID_APL_SRC" NUMBER, 
	"AGM_ID_TPE" NUMBER, 
	"PRD_EXT_REF" VARCHAR2(50 ), 
	"PRD_ID_APL_SRC" NUMBER, 
	"PRD_ID_TPE" NUMBER, 
	"CODE" VARCHAR2(50 ), 
	"DT_BEG" DATE, 
	"DT_END" DATE, 
	"ST_PLC" NUMBER, 
	"ST_PLC_DTL" NUMBER, 
	"ID_CDE_CY" NUMBER, 
	"DT_CRT_PLC" DATE, 
	"DT_VLD_BSN_BEG" DATE, 
	"DT_VLD_SRC_BEG" DATE, 
	"SEQ_PLC_CHG" NUMBER, 
	"ID_APL_SRC" NUMBER, 
	"ID_TPE" NUMBER, 
	"ID_LOAD" NUMBER, 
	"TP_PLC" NUMBER,
    ID_PRT VARCHAR2(20),
    AGM_ID_PRT VARCHAR2(20),
    PRD_ID_PRT VARCHAR2(20)
   );

CREATE OR REPLACE TABLE GEN_PLC_CMP
   (	"ID_SLOT" NUMBER, 
	"AGM_EXT_REF_PLC" VARCHAR2(50 ), 
	"AGM_ID_APL_SRC_PLC" NUMBER, 
	"AGM_ID_TPE_PLC" NUMBER, 
	"AGM_EXT_REF" VARCHAR2(60 ), 
	"AGM_ID_APL_SRC" NUMBER, 
	"AGM_ID_TPE" NUMBER, 
	"AGM_EXT_REF_PARENT" VARCHAR2(50 ), 
	"AGM_ID_APL_SRC_PARENT" NUMBER, 
	"AGM_ID_TPE_PARENT" NUMBER, 
	"PRD_EXT_REF" VARCHAR2(50 ), 
	"PRD_ID_APL_SRC" NUMBER, 
	"PRD_ID_TPE" NUMBER, 
	"CODE" VARCHAR2(100 ), 
	"ST_PLC_CMP_DTL" NUMBER, 
	"DT_BEG" DATE, 
	"DT_END" DATE, 
	"ST_PLC_CMP" NUMBER, 
	"DT_VLD_BSN_BEG" DATE, 
	"DT_VLD_SRC_BEG" DATE, 
	"SEQ_PLC_CHG" NUMBER, 
	"ID_APL_SRC" NUMBER, 
	"ID_TPE" NUMBER, 
	"ID_LOAD" NUMBER, 
	"ID_PRT" VARCHAR2(81 ),
	"TP_PLC_CMP" NUMBER, 
	"PRD_ID_PRT" VARCHAR2(9 ),
	"AGM_ID_PRT_PARENT" VARCHAR2(9 ),
	"AGM_ID_PRT" VARCHAR2(9 ),
	"AGM_ID_PRT_PLC" VARCHAR2(9 )
   )
;

CREATE OR REPLACE TABLE A_AGM
   (	"ID_AGM" NUMBER, 
	"ID_APL_SRC" NUMBER, 
	"ID_TPE" NUMBER, 
	"EXT_REF" VARCHAR2(60 ) , 
	"ID_LOAD" NUMBER,
    "ID_PRT" VARCHAR2(81 ) 
   );

CREATE OR REPLACE SEQUENCE SEQ_A_AGM;

CREATE OR REPLACE TABLE PLC
   (	"SID_PLC" NUMBER, 
	"ID_AGM" NUMBER, 
	"ID_PRD" NUMBER, 
	"CODE" VARCHAR2(50 ), 
	"DT_BEG" DATE, 
	"DT_END" DATE, 
	"ST_PLC" NUMBER, 
	"ST_PLC_DTL" NUMBER, 
	"ID_CDE_CY" NUMBER, 
	"DT_CRT_PLC" DATE, 
	"DT_VLD_BSN_BEG" DATE, 
	"DT_VLD_SRC_BEG" DATE, 
	"DT_VLD_SRC_END" DATE, 
	"SEQ_PLC_CHG" NUMBER, 
	"ID_APL_SRC" NUMBER, 
	"ID_TPE" NUMBER, 
	"ID_LOAD" NUMBER, 
	"ID_PRT" VARCHAR2(81 ) , 
	"TP_PLC" NUMBER
  );

CREATE OR REPLACE SEQUENCE SEQ_PLC;

CREATE OR REPLACE TABLE PLC_CMP
   (	"SID_PLC_CMP" NUMBER, 
	"ID_AGM_PLC" NUMBER, 
	"ID_AGM" NUMBER, 
	"ID_AGM_PARENT" NUMBER, 
	"ID_PRD" NUMBER, 
	"CODE" VARCHAR2(100 ), 
	"ST_PLC_CMP_DTL" NUMBER, 
	"DT_BEG" DATE, 
	"DT_END" DATE, 
	"ST_PLC_CMP" NUMBER, 
	"DT_VLD_BSN_BEG" DATE, 
	"DT_VLD_SRC_BEG" DATE, 
	"DT_VLD_SRC_END" DATE, 
	"SEQ_PLC_CHG" NUMBER, 
	"ID_APL_SRC" NUMBER, 
	"ID_TPE" NUMBER, 
	"ID_LOAD" NUMBER, 
	"ID_PRT" VARCHAR2(81 )   ,
	"TP_PLC_CMP" NUMBER
   );

CREATE OR REPLACE SEQUENCE SEQ_PLC_CMP;

CREATE OR REPLACE TABLE LD_RID
   (	"RID" NUMBER, 
	"DT_VLD_SRC_BEG" DATE, 
	"DT_VLD_SRC_END" DATE
   );

